const { GitContentSource } = require("@stackbit/cms-git");

module.exports = {
  stackbitVersion: '~0.6.0',
  ssgName: 'eleventy',
  nodeVersion: '20',

  contentSources: [
    new GitContentSource({
      rootPath: __dirname,
      contentDirs: ["src"],
      models: [
        {
          name: "page",
          type: "page",
          label: "Page",
          filePath: "src/pages/{slug}.md",
          fields: [
            { name: "title", type: "string", required: true },
            { name: "body", type: "markdown" }
          ]
        },
        {
          name: "post",
          type: "page",
          label: "Blog Post",
          filePath: "src/posts/{slug}.md",
          fields: [
            { name: "title", type: "string", required: true },
            { name: "date", type: "date" },
            { name: "body", type: "markdown" }
          ]
        }
      ],
    })
  ],

  /**
   * SITE MAP FUNCTION
   * Maps local file paths to the actual URLs generated by Eleventy.
   */
  siteMap: ({ documents, models }) => {
    const pageModels = models
      .filter((m) => m.type === "page")
      .map((m) => m.name);

    return documents
      .filter((d) => pageModels.includes(d.modelName))
      .map((document) => {
        let url = "/";

        // Logic based on Dante's folder/model structure
        switch (document.modelName) {
          case 'page':
            // Example: src/pages/about.md -> /about/
            url = `/${document.id.replace('src/pages/', '').replace('.md', '')}`;
            break;
          case 'post':
            // Example: src/posts/my-post.md -> /blog/my-post/
            url = `/blog/${document.id.replace('src/posts/', '').replace('.md', '')}`;
            break;
          default:
            return null;
        }

        // Clean up double slashes and ensure a leading slash
        const normalizedUrl = url.replace(/\/+/g, '/');

        return {
          stableId: document.id,
          urlPath: normalizedUrl,
          document,
          // Set home page if file is src/pages/index.md
          isHomePage: document.id === 'src/pages/index.md'
        };
      })
      .filter(Boolean);
  }
};